#服务端口
server:
  port: 8002
#服务名

spring:
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.223.132:8848
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev

##阿里云 OSS
aliyun:
  oss:
    file:
      #不同的服务器，地址不同
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tFvPbc1HrJJGuwii5jp
      keysecret: ujLm6oOhSv16Epyv46eNbLYCoGN6iR
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-sys-terriss