# 服务端口
server:
  port: 8004

spring:
  # 需要将其设置为always，彩色打印日志
  output:
    ansi:
      enabled: always
  # 配置redis
  redis:
    # redis服务器地址
    host: 192.168.223.132
    # 端口号
    port: 6379
    # redis数据库索引（默认0）
    database: 0
    # 连接超时时间
    timeout: 1800000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 最大阻塞等待时间
        max-wait: 1
        # 连接池中最大的空闲连接
        max-idle: 5
        # 连接池中最小的空闲连接
        min-idle: 0
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.223.132:8848
  # 映射resource.static下文件，使之可以通过url地址直接访问
  mvc:
    static-path-pattern: /**
  application:
    # 服务名
    name: service-cms
  # 环境配置
  profiles:
    active: dev
  # mysql连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.132:7777/edu_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # 配置mapper xml文件路径
  mapper-locations: classpath:com/example/terrissedu/mapper/xml/*.xml
  # mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
