#服务端口
server:
  port: 8003
#服务名

spring:
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.223.132:8848
  application:
    name: service-vod
  #环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB


#阿里云 OSS
aliyun:
  oss:
    file:
      keyid: LTAI5tFvPbc1HrJJGuwii5jp
      keysecret: ujLm6oOhSv16Epyv46eNbLYCoGN6iR