# 服务端口
server:
  port: 8101

spring:
  # 需要将其设置为always，彩色打印日志
  output:
    ansi:
      enabled: always
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.223.132:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         #设置路由id
       - id: service-acl
         #设置路由的uri
         uri: http://localhost:8333
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
         - Path=/*/acl/**
        #设置路由id
       - id: service-cms
         #设置路由的uri
         uri: http://localhost:8004
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
         - Path=/cms-service/**
        #设置路由id
       - id: service-edu
         #设置路由的uri
         uri: http://localhost:8001
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
         - Path=/edu-service/**
        #设置路由id
       - id: service-order
         #设置路由的uri
         uri: http://localhost:8006
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
           - Path=/order-service/**
        #设置路由id
       - id: service-oss
         #设置路由的uri
         uri: http://localhost:8002
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
           - Path=/edu-oss/**
        #设置路由id
       - id: service-sms
         #设置路由的uri
         uri: http://localhost:8005
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
           - Path=/sms-service/**
        #设置路由id
       - id: service-static
         #设置路由的uri
         uri: http://localhost:8007
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
           - Path=/static-service/**
        #设置路由id
       - id: service-user
         #设置路由的uri
         uri: http://localhost:8160
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
           - Path=/user-service/**
        #设置路由id
       - id: service-vod
         #设置路由的uri
         uri: http://localhost:8003
         #设置路由断言,代理servicerId为auth-service的/auth/路径
         predicates:
           - Path=/edu-vod/**
  application:
    # 服务名
    name: gateway-api
